from typing import Optional, Protocol, List
from models import Job, Status, Radar, group_id, job_id
from models.responses.results import Response


class JobStoreProtocol(Protocol):
    def add_job(self) -> Job: ...
    def get_job(self, job_id: job_id) -> Job: ...
    def update_job(self, job: Job, status: Status, error: Optional[str] = None): ...
    def add_results(self, job: Job, responses: List[Response]): ...
    def get_results_by_job_id(
        self, job_id: job_id, page: int = 0, page_size: int = 0
    ) -> List[Response]: ...
    def get_results_by_group_id(
        self, group_id: group_id, page: int = 0, page_size: int = 0
    ) -> List[Response]: ...
