from typing import Protocol, List
from models import Job, Status, Radar, group_id, job_id


class JobStoreProtocol(Protocol):
    def add_job(self) -> Job: ...
    def get_job(self, job_id: int) -> Job: ...
    def update_job(self, job_id: int, status: Status): ...
    def add_results(self, job: Job, radars: List[Radar]): ...
    def get_results_by_job_id(
        self, job_id: job_id, page: int = 0, page_size: int = 0
    ) -> List[Radar]: ...
    def get_results_by_group_id(
        self, group_id: group_id, page: int = 0, page_size: int = 0
    ) -> List[Radar]: ...
